# Generated by Django 4.2 on 2023-04-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pointOfContact', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('contractor', models.CharField(choices=[('GNM', 'Genomed'), ('AA', 'A&A')], max_length=16)),
                ('finishDate', models.DateField()),
                ('status', models.CharField(choices=[('AW', 'Oczekuje'), ('RCV', 'Otrzymano'), ('IP', 'W realizacji'), ('SNT', 'Wysłano'), ('FIN', 'Zakończono'), ('CAN', 'Anulowano')], max_length=16)),
                ('notes', models.TextField()),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('unit', models.CharField(choices=[('CNT', 'Liczba reakcji'), ('SET', 'Zestaw')], max_length=16)),
                ('count', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('ADD', 'Dodanie'), ('REM', 'Usunięcie')], max_length=16)),
                ('notes', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.company')),
            ],
        ),
    ]
