# Generated by Django 4.2 on 2023-04-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phoneNumber',
            field=models.CharField(max_length=64, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pointOfContact',
            field=models.CharField(max_length=64, verbose_name='Osoba kontaktowa'),
        ),
    ]
