# Generated by Django 4.2 on 2023-04-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_company_email_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='phoneNumber',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='pointOfContact',
            field=models.CharField(max_length=64),
        ),
    ]
