# Generated by Django 4.2 on 2023-04-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_order_files_alter_order_contractor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedfile',
            old_name='upload',
            new_name='file',
        ),
    ]
