# Generated by Django 4.2 on 2023-04-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_upload_linkedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contractor',
        ),
    ]
