# Generated by Django 4.2 on 2023-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_remove_order_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contractor',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
